# Generated by Django 4.1.7 on 2023-08-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Is Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
