# Generated by Django 4.1.7 on 2023-09-04 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_patient_profile_pic_alter_symptom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chronic_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chronic Condition'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 2, 4, 40, 943073)),
        ),
    ]
