# Generated by Django 4.1.7 on 2023-09-04 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_patient_notes_alter_symptom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 18, 29, 20, 552096)),
        ),
    ]
