# Generated by Django 4.1.7 on 2023-09-06 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_symptom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chronic Conditions'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 18, 21, 20, 403055)),
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 6, 18, 21, 20, 403394))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='operations.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
