# Generated by Django 4.1.7 on 2023-09-07 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_patient_chronic_condition_alter_symptom_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='past_30_days_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Past 30 Days'),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_90_days_condition',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Past 90 Days'),
        ),
        migrations.AddField(
            model_name='patient',
            name='recent_illness',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Recent Illness'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 1, 27, 35, 131419)),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 1, 27, 35, 131072)),
        ),
    ]
