# Generated by Django 4.1.7 on 2023-09-08 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_patient_past_30_days_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 21, 9, 19, 441708)),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 21, 9, 19, 441253)),
        ),
    ]
